# Generated by Django 4.2.6 on 2023-10-21 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0005_emailaddress_idx_upper_email'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('socialaccount', '0005_socialtoken_nullable_app'),
        ('app', '0002_customuser_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
